image: node:6.7.0

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "StrictHostKeyChecking no " > /root/.ssh/config
    - npm --registry=https://registry.npm.taobao.org install
    - npm run compile
  only:
    - master
  tags:
    - build-node

deploy:
  stage: deploy
  script:
    - cd /home/ops/production/fundGateway
    - git checkout master
    - git reset --hard HEAD
    - rm -Rf dist
    - git pull
    - npm --registry=https://registry.npm.taobao.org install
    - npm run compile
    - pm2 restart fundGateway
  only:
    - master
  tags:
    - deploy-ssh
