image: node:6.7.0

cache:
  paths:
    - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd /home/ops/production/fundGateway
    - git checkout master
    - git reset --hard HEAD
    - git clean -f -d
    - git pull
    - npm install --registry=https://registry.npm.taobao.org
    - pm2 restart fundGateway
  only:
    - master
  tags:
    - deploy-ssh
